[build]
  publish = "dist/public"
  command = "npm ci && NODE_ENV=production npx vite build --config vite.config.production.js && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200