[build]
  publish = "dist/public"
  command = "npm install && mkdir -p dist/public && npx esbuild client/src/main.tsx --bundle --outfile=dist/public/main.js --format=iife --target=es2020 --jsx=automatic --define:process.env.NODE_ENV='\"production\"' && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && node fix-html.js"

[build.environment]
  NODE_VERSION = "20.17.0"
  NODE_ENV = "production"
  DISABLE_REPLIT_PLUGINS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
