[build]
  publish = "dist/public"
  command = "node build-netlify.js"

[build.environment]
  NODE_VERSION = "20.17.0"
  NODE_ENV = "production"
  DISABLE_REPLIT_PLUGINS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
