[build]
  publish = "dist/public"
  command = "npm ci && DISABLE_REPLIT_PLUGINS=true NODE_ENV=production npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[build.environment]
  NODE_VERSION = "20.17.0"
  NODE_ENV = "production"
  DISABLE_REPLIT_PLUGINS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
