[build]
  publish = "dist/public"
  command = "npm ci && REPL_ID= NODE_ENV=production npx vite build"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"